name: S3 Backup
on:
  push:
    branches:
      - master
jobs:
  s3Backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: S3 Backup
        uses: peter-evans/s3-backup@v1
        env:
          ACCESS_KEY_ID: ${{ secrets.AWS_S3_BUCKET_ACCESS_KEY_ID }}
          MIRROR_TARGET: ${{ secrets.AWS_S3_BUCKET_MIRROR_TARGET }}/${{ github.repository }}
          SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_BUCKET_SECRET_ACCESS_KEY }}
        with:
          args: --overwrite --remove
